[package]
name = "gekkio-ftdi-bindgen"
version = "0.0.0"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
publish = false

[dependencies]
bindgen = "0.49"
failure = "0.1"
